import {
  Box,
  Button,
  Container,
  Grid,
  Typography,
  styled,
  useTheme,
} from "@mui/material";
import SmartToyOutlinedIcon from "@mui/icons-material/SmartToyOutlined";
import AssuredWorkloadOutlinedIcon from "@mui/icons-material/AssuredWorkloadOutlined";
import HandymanOutlinedIcon from "@mui/icons-material/HandymanOutlined";
import { useNavigate } from "react-router-dom";

const TypographyH1 = styled(Typography)(
  ({ theme }) => `
    font-size: ${theme.typography.pxToRem(50)};
`
);

const TypographyH2 = styled(Typography)(
  ({ theme }) => `
    font-size: ${theme.typography.pxToRem(17)};
`
);

const LabelWrapper = styled(Box)(
  ({ theme }) => `
    background-color: ${theme.palette.secondary[300]};
    color: ${theme.palette.primary[400]};
    font-weight: bold;
    border-radius: 30px;
    text-transform: uppercase;
    display: inline-block;
    font-size: ${theme.typography.pxToRem(11)};
    padding: ${theme.spacing(0.5)} ${theme.spacing(1.5)};
    margin-bottom: ${theme.spacing(2)};
`
);

const AvatarBox = styled(Box)(
  ({ theme }) => `
    width: ${theme.spacing(8)};
    height: ${theme.spacing(8)};
    border-radius: ${`7px`};
    background-color:  ${theme.palette.grey[100]};
    color: ${theme.palette.primary[700]};
    flex-shrink: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    margin: 0 auto ${theme.spacing(2)};

    img {
      width: 60%;
      height: 60%;
      display: block;
    }
`
);

const Home = () => {
  const theme = useTheme();
  const navigate = useNavigate();
  return (
    <Container maxWidth="lg" sx={{ textAlign: "center" }}>
      <Grid
        spacing={{ xs: 6, md: 10 }}
        justifyContent="center"
        alignItems="center"
        container
      >
        <Grid item md={10} lg={8} mx="auto">
          <LabelWrapper color="success">Version 1.0.0</LabelWrapper>
          <TypographyH1 sx={{ mb: 2 }} variant="h1">
            Discover the Infinite Possibilities of AI-Generated Art
          </TypographyH1>
          <TypographyH2
            sx={{ lineHeight: 1.5, pb: 4 }}
            variant="h4"
            color="text.secondary"
            fontWeight="normal"
          >
            Unleash Your Creativity with Magpie's Melange NFT Collection.
          </TypographyH2>
          <Button
            onClick={() => {
              navigate(`/mint`);
            }}
            size="large"
            variant="contained"
            sx={{
              backgroundColor: theme.palette.secondary[300],
              color: theme.palette.primary[400],
            }}
          >
            Mint Your Own NFT
          </Button>
          <Button
            onClick={() => {
              navigate(`/collection`);
            }}
            sx={{ ml: 2, color: theme.palette.secondary[300] }}
            size="large"
            variant="text"
          >
            View Latest Additions
          </Button>
          <Grid container spacing={3} mt={5}>
            <Grid item md={4}>
              <AvatarBox>
                <SmartToyOutlinedIcon fontSize="large" />
              </AvatarBox>
              <Typography variant="h4">
                <Box sx={{ pb: 2 }}>
                  <b>AI-generated NFTs</b>
                </Box>
                <Typography component="span" variant="subtitle2">
                  The NFTs in this collection are generated by AI models using
                  text prompts from users.
                </Typography>
              </Typography>
            </Grid>
            <Grid item md={4}>
              <AvatarBox>
                <AssuredWorkloadOutlinedIcon fontSize="large" />
              </AvatarBox>
              <Typography variant="h4">
                <Box sx={{ pb: 2 }}>
                  <b>Lifetime Royalties</b>
                </Box>
                <Typography component="span" variant="subtitle2">
                  Minters of the NFTs will earn lifetime royalties for any
                  secondary sales of their NFTs.
                </Typography>
              </Typography>
            </Grid>
            <Grid item md={4}>
              <AvatarBox>
                <HandymanOutlinedIcon fontSize="large" />
              </AvatarBox>
              <Typography variant="h4">
                <Box sx={{ pb: 2 }}>
                  <b>Utility</b>
                </Box>
                <Typography component="span" variant="subtitle2">
                  Holders of the NFTs can upload PDF files to train AI models
                  for document processing and interaction.
                </Typography>
              </Typography>
            </Grid>
          </Grid>
        </Grid>
      </Grid>
    </Container>
  );
};

export default Home;
